### ISSUE TITLE
Add initial registry kind tests

### ISSUE THREAD

**Issue by denis-tingajkin** [networkservicemesh/integration-k8s-kind#1]
## Description

We need to start thinking about integration testing via k8s. We can start with a simple approach: 
1. Store all deployments in this repository.  _For example, we can store all deployments in folder /deployments and after some_ time we can move it to separate repository.
2. Use yaml deployments in this repository.
3. Use extra needed applications in this repository. _For example, we can add some clients endpoints applications into folder /cmd and we can get rit of it when all nsm applications will be completed_
4.  Use go tests that should be based on user steps. For this we can use exechelper and k8s-go-client.

**Comment by haiodo** [comment]
I prefer to use cloudtest with one cluster setup, since it will allow easy junit line integration, and potentially only different cloud test config will be required for kind/aws etc configurations.

Also I'm not sure yaml approach is very robust in compare to fully API approach we have in monorepo, since most complex parts is not push yaml configuration but, to wait for pod to be ready to use. But we could mix I think.

**Comment by denis-tingajkin** [comment]
I'm not sure that we need to use cloudtest for a single cluster tests right now because it looks overpowering to me. But I think we should use cloudtest for interdomain tests.
